Repository gnu-octave/packages, pull requests merged in 2022-07, with the labels that each got.

#126 symbolic: switch main branch name to "main"
  packages/symbolic.yaml
Labels: documentation

#127 Reference Octave 7 under ubuntu2204
  CONTRIBUTING.md
Labels: documentation

#128 Symbolic 3.0.0 release
  packages/symbolic.yaml
Labels: package release

#133 Update vrml.yaml
  packages/vrml.yaml
Labels: enhancement

#130 New package: "internal-fluid-flow"
  packages/internal-fluid-flow.yaml
Labels: new package

#142 packages/internal-fluid-flow.yaml: restore previous version
  packages/internal-fluid-flow.yaml
Labels: enhancement

#138 Create Automatic Differentiation
  packages/automatic-differentiation.yaml
Labels: new package

#146 bim release 1.1.6
  packages/bim.yaml
  packages/msh.yaml
Labels: package release

#147 packages/msh.yaml: improve spec
  packages/msh.yaml
Labels: enhancement

#148 packages/bim.yaml: improve spec
  packages/bim.yaml
Labels: enhancement

#149 new release of msh package 1.0.12
  packages/msh.yaml
Labels: package release
