Repository gnu-octave/packages, pull requests merged in 2024-02, with the labels that each got.

#405 Update website_build_deploy.yml: use recommended `ruby/setup-ruby@v1`
  .github/workflows/website_build_deploy.yml
Labels: enhancement

#406 Update website_build_deploy.yml: use same Ruby version as in `main.yml`
  .github/workflows/website_build_deploy.yml
Labels: bug

#407 Update website_build_deploy.yml: update `actions/upload-pages-artifact@v3`
  .github/workflows/website_build_deploy.yml
Labels: bug

#412 Update statistics-resampling.yaml
  packages/statistics-resampling.yaml
Labels: package release
